// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnek_m0GHz4x7hO2Ux2JGxs9TmUB_4chY',
    appId: '1:121034384108:web:e1c98d25058a9a78f0fbc9',
    messagingSenderId: '121034384108',
    projectId: 'myexamflutter1',
    authDomain: 'myexamflutter1.firebaseapp.com',
    storageBucket: 'myexamflutter1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DgOZ4S7G1TA_E2buJ8a5L_XLMjjjyOc',
    appId: '1:121034384108:android:8aee384338978b9df0fbc9',
    messagingSenderId: '121034384108',
    projectId: 'myexamflutter1',
    storageBucket: 'myexamflutter1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHnSpb8RDt8kYlOdc_EbL_u1XJq1JY6lw',
    appId: '1:121034384108:ios:df2865867f338e6ff0fbc9',
    messagingSenderId: '121034384108',
    projectId: 'myexamflutter1',
    storageBucket: 'myexamflutter1.appspot.com',
    androidClientId: '121034384108-e9vbm7v5htsfij94cj27no9ucj39g34d.apps.googleusercontent.com',
    iosClientId: '121034384108-k3321qu4hhh3pr6pkknucl2q5s0ikkui.apps.googleusercontent.com',
    iosBundleId: 'com.example.examApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHnSpb8RDt8kYlOdc_EbL_u1XJq1JY6lw',
    appId: '1:121034384108:ios:df2865867f338e6ff0fbc9',
    messagingSenderId: '121034384108',
    projectId: 'myexamflutter1',
    storageBucket: 'myexamflutter1.appspot.com',
    androidClientId: '121034384108-e9vbm7v5htsfij94cj27no9ucj39g34d.apps.googleusercontent.com',
    iosClientId: '121034384108-k3321qu4hhh3pr6pkknucl2q5s0ikkui.apps.googleusercontent.com',
    iosBundleId: 'com.example.examApp',
  );
}
